import:
  - source: ./windows.yml
    mode: merge
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install conan
# command to run tests
script:
  - echo "HELLO! ${CONAN_STUFF}"
